- name: OS Patching
  hosts: all
  tasks:
    - name: Install repo
      yum:
        name: epel-release
        state: latest
        update_cache: yes
    - name: Update system
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: Install common packages
      yum:
        name: ["bind-utils", "man", "man-pages", "mlocate", "sysstat"]
        state: latest
    - name: edit sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: '^\#PermitRootLogin yes'
        state: present
        line: 'PermitRootLogin no'
    - name: restart sshd
      service:
        name: sshd
        state: restarted